title: Without A Path
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
locale: en_US

kramdown:
  html_to_native: true

gems:
  - jekyll-paginate-v2

# plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank

# jekyll-seo-tag
twitter:
  username: BaurJoe
  card: summary_large_image
facebook:
  app_id: 724033991719152
  publisher: 1234
  admins: 1234
social:
  name: Joe Baur
  links:
    - https://instagram.com/BaurJoe
    - https://twitter.com/BaurJoe
    - https://www.facebook.com/BaurJoe
    - http://www.youtube.com/user/MildlyRelevant/
webmaster_verifications:
  google: diU23OclJ1EoZzWYSp1qWcn9ujRhXfx0XUS3lFrF5zM
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
lang: en_US
google-analytics: UA-24585508-2

# post permalinks
permalink: /:title/

# Instagram feed by https://github.com/stevenschobert/instafeed.js/
instafeed-app: https://xxx.herokuapp.com/token.js

# jekyll-cloudinary
cloudinary:
  cloud_name: withoutapath
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo

# jekyll-feed
feed:
  excerpt_only: false
  posts_limit: 20

#albolia search 
algolia:
  application_id: SI1WCX3GH6
  index_name: Without A Path
  search_only_api_key: 98f196107753a99f5f29dc5f64aa0c94

include:
  - _pages
  - _travel-guides

# defaults
defaults:
  - scope:
      path: ""
    values:
      author: "joebaur"
      layout: "page"
      image: /assets/img/grumpy.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/img/grumpy.jpg

# collections
collections:
  authors:
    output: false
  travel-guides:
    output: true

autopages:
  enabled: enabled
  categories: 
    layouts: 
      - 'blog.html'
    title: ':cat'
    permalink: '/category/:cat'
    slugify:
      mode: 'default'
      case: true
  collections:
    layouts: 
      - 'blog.html'
    title: ':coll'
    permalink: '/collection/:coll'
    slugify:
      mode: 'default'
      case: true 
  tags:
    layouts: 
      - 'blog.html'
    title: ':tag'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'
      case: true

# Pagination Settings https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  enabled: true
  per_page: 9
  permalink: '/page-:num/'
  title: ':title'
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

# contact info 
email: joe@joebaur.com
address: A108 Adam Street, New York, NY 535022
phone: +1 559 554 8855
google-maps-embed: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d77672.07668705504!2d13.334068693876274!3d52.52886744871557!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sde!4v1594751666546!5m2!1sen!2sde
formspree: mbjzpoqw
mailchimp-list: 1234
github_username:  BaurJoe
disqus: "withoutapath"
social:
  twitter: BaurJoe
  facebook: BaurJoe
  instagram: BaurJoe
  youtube: MildlyRelevant
  soundcloud: without-a-path
  linkedin: 

compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []
