title: Without A Path
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://withoutapath.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus: "withoutapath"
locale: en_US

kramdown:
  html_to_native: true

gems:
  - jekyll-paginate-v2

# plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank

# jekyll-seo-tag
twitter:
  username: BaurJoe
  card: summary_large_image
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234
social:
  name: Joe Baur
  links:
    - https://instagram.com/BaurJoe
    - https://twitter.com/BaurJoe
    - https://www.facebook.com/BaurJoe
    - http://www.youtube.com/user/MildlyRelevant/
webmaster_verifications:
  google: diU23OclJ1EoZzWYSp1qWcn9ujRhXfx0XUS3lFrF5zM
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
lang: en_US
google-analytics: UA-24585508-2

# post permalinks
permalink: /:title/

# jekyll-cloudinary
cloudinary:
  cloud_name: withoutapath
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo

# jekyll-feed
feed:
  path: atom.xml
  excerpt_only: true

include:
 - _pages

# defaults
defaults:
  - scope:
      path: ""
    values:
      author: "joebaur"
      layout: "page"
      image: /assets/img/grumpy.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/img/grumpy.jpg

# collections
collections:
  authors:
    output: false

autopages:
  enabled: enabled
  categories: 
    layouts: 
      - 'autopage_category.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: 'default'
      case: true
  collections:
    layouts: 
      - 'autopage_collection.html'
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    slugify:
      mode: 'default'
      case: true 
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'
      case: true

# Pagination Settings
pagination:
  enabled: true
  collection: 'posts'
  per_page: 9
  permalink: '/page-:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# contact info 
email: joe@joebaur.com
address: A108 Adam Street, New York, NY 535022
phone: +1 559 554 8855
google-maps-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d38842.872214853356!2d13.368744298832484!3d52.52113878672291!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a84e373f035901%3A0x42120465b5e3b70!2sBerlin!5e0!3m2!1sen!2sde!4v1594716411672!5m2!1sen!2sde
formspree: mbjzpoqw